### PR TITLE
rectprops update

### PR DESCRIPTION
**Pull request by afni-dglen**
Re-forked and new pull request to implement changes for deprecated rectprops with props in matplotlib function call. This version checks for older  versions of matplotlib to continue with old behavior.

### CODE REVIEW

**Comment by rgbayrak** [comment]
@smoia do you know what is this check that failed? .pre-commit-config.yaml is not a file

**Comment by smoia** [comment]
Hey @afni-dglen ! Could you rebase this PR on the latest master? This should take care of a few issues. After that, @maestroque , do you want to give a try at a PR review? Otherwise @me-pic and @m-miedema could help with it?

**Review by maestroque — COMMENTED** [review]
If we are going to allow all matplotlib versions, we should remove [the dependency constraint in `setup.cfg`](https://github.com/physiopy/peakdet/blob/master/setup.cfg#L24)

**Comment by maestroque** [comment]
Hey @afni-dglen ! 
I believe the things that remain for this PR are:
- rebasing from master branch (this will also take care of pre-commit because it was added in a later patch)
- removing the matplotlib constraint from `setup.cfg`

This PR is currently blocking https://github.com/physiopy/phys2denoise/pull/54, due to the incompatibility of matplotlib throughout `peakdet`, `phys2denoise` and `physutils`, so it would be really appreciated if this could be handled soon.

Btw @smoia I think once this is merged we should do a new release in peakdet, since the current release is already outdated, and clones dependencies such as gooey and wxpython.

**Comment by maestroque** [comment]
Also, another question is that could we just change the version here at `>=3.9`, as in `phys2denoise` and `physutils` and settle with `props` instead?
Is there any other compatibility issue with other packages I'm missing?

**Comment by afni-dglen** [comment]
I think I took care of both those issues. Rebasing was problematic, so another fork and a new pull request.

https://github.com/physiopy/peakdet/pull/74

I'll close this one then.

**Pull request closed without merging**
