### PR TITLE
Add auto-author and auto-label to github workflow 

### LINKED ISSUE #64: Implement auto-author-assign and auto-label workflows
The same as this issue in phys2bids (https://github.com/physiopy/phys2bids/issues/465) but implement for this repo

### PR DESCRIPTION
**Pull request by RayStick**
Closes #64 

## Proposed Changes

  - The same as [this PR for phys2bids](https://github.com/physiopy/phys2bids/pull/466) but implemented for this repo
  - All I did was change the directory locations in the .github/labeler.yml file, otherwise the files are the same as the phys2bids files
  
## Change Type

- [ ] `bugfix` (+0.0.1)
- [ ] `minor` (+0.1.0)
- [ ] `major`  (+1.0.0)
- [ ] `refactoring` (no version update)
- [ ] `test` (no version update)
- [x] `infrastructure` (no version update)
- [ ] `documentation` (no version update)
- [ ] `other`

## Checklist before review

- [x] I added everything I wanted to add to this PR.
- [ ] \[Code or tests only\] I wrote/updated the necessary docstrings.
- [ ] \[Code or tests only\] I ran and passed tests locally.
- [ ] \[Documentation only\] I built the docs locally.
- [x] My contribution is harmonious with the rest of the code: I'm not introducing repetitions.
- [ ] My code respects the adopted style, especially linting conventions.
- [x] The title of this PR is explanatory on its own, enough to be understood as part of a changelog.
- [x] I added or indicated the right labels.

- [ ] I added information regarding the timeline of completion for this PR.

- [x] Please, comment on my PR while it's a draft and give me feedback on the development!

### CODE REVIEW

**Comment by RayStick** [comment]
@smoia ready to review but pre-commit is not happy

**Comment by maestroque** [comment]
@RayStick pre-commit is failing because it is not yet configured for this repository.
After #67 is merged then this could be merged as well, since it's already integrated to `phys2bids` (although order shouldn't matter).

**Comment by RayStick** [comment]
@maestroque ah great, thanks for the context! Will wait for #67 then

**Comment by maestroque** [comment]
@RayStick #67 is now merged! You could now pull from the master branch, and this should be ready to go

**Review by maestroque — APPROVED** [review]

**Comment by RayStick** [comment]
Thank you @maestroque!

**Comment by smoia** [comment]
:rocket: PR was released in [`0.4.0`](https://github.com/physiopy/peakdet/releases/tag/0.4.0) :rocket:

**Pull request merged**
