### PR TITLE
Add all-contributors

### LINKED ISSUE #29: Recognise current contributions and cut a release of peakdet _before_ its "physiopy stage".
As this package moved into peakdet, it would be better to track its former development and the moment it changed ownership with a release cut. @rmarkello, which development stage (hence what version) do you think is more appropriate for this version of `peakdet`? `0.1.0` or `1.0.0`?
Before cutting a release, I would also like to adopt the all-contributors specification to recognise @rmarkello @emdupre @xl624 contributions. Can I kindly ask the three of you to propose your contribution types?

### PR DESCRIPTION
**Pull request by smoia**
Closes #29 .

## Proposed changes
- Add all-contributors to track contributions!

### CODE REVIEW

**Comment by tsalo** [comment]
The `rmarkello` --> `physiopy` changes are going to conflict with #34, aren't they?

**Comment by smoia** [comment]
They might, yes. We should merge #34 before this one!

**Comment by smoia** [comment]
@tsalo I didn't realise I based this branch on #34. I changed it to base it on current master!

**Comment by tsalo** [comment]
Since you're creating a new README.md file, I think you should probably delete the README.rst file as well.

**Comment by smoia** [comment]
I thought so to, but I'm quite positive about the fact that `README.rst` is the home page of the documentation. If it's not, I'm happy to take it away, but otherwise it would call for restructuring documentation (which should become another PR).

**Review by tsalo — APPROVED** [review]

**Comment by tsalo** [comment]
Switching from rst to md should be relatively easy if the README is used in the documentation. We'll need to include `mdinclude` in the dependencies and use that, although I recall there being a bug. Still, it's something I've dealt with in NiMARE and possibly other repos.

**Review by eurunuela — APPROVED** [review]
LGTM!

**Pull request merged**
